/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_ThermalMeter
#define HEADER_ThermalMeter
/*
htop - ThermalMeter.h
(C) 2017 Allen Wild
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"
extern void ThermalMeter_init(Meter *this);
extern void ThermalMeter_updateValues(Meter *this, char *buf, int size);

extern int ThermalMeter_attributes[];

extern MeterClass ThermalMeter_class;

#endif
