/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Thermal
#define HEADER_Thermal
/*
htop - Thermal.h
(C) 2017 Allen Wild
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

void ThermalMeter_init(Meter *this);

void ThermalMeter_updateValues(Meter *this, char *buf, int size);

#endif
